name: Main

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version for tag
        if: github.ref_type == 'tag'
        run: echo "version=$(git describe --tags --match 'v*')" >> $GITHUB_ENV

      - name: Set version for branch
        if: github.ref_type == 'branch'
        run: echo "version=$(git describe --tags)" >> $GITHUB_ENV

      - name: Build
        env:
          DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
        run: |
          xcodebuild archive -project Microphone.xcodeproj -scheme Microphone -configuration Release -archivePath Microphone.xcarchive MARKETING_VERSION=${{github.ref_name}}
          xcodebuild archive -archivePath Microphone.xcarchive -exportArchive -exportOptionsPlist export_options.plist -exportPath .
          zip -r "Microphone-${{env.version}}.zip" "Microphone.app"

      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: Microphone-${{env.version}}.zip

      - name: Prerelease
        if: github.ref_type == 'branch'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: prerelease
          prerelease: true
          files: Microphona-${{env.version}}.zip
